ifneq ($(MAKECMDGOALS),clean) # ignore check for make clean

ifeq ($(AM_HOME),) # AM_HOME must exist
$(error Environment variable AM_HOME must be defined.)
endif

ifeq ($(MIPS32_NEMU_HOME),) # MIPS32_NEMU_HOME must exist
$(error Environment variable MIPS32_NEMU_HOME must be defined.)
endif

endif
